#!/usr/bin/env ruby

require "mintkit"

ENV['RAILS_ENV'] = "development"
require "../config/environment.rb"

if ARGV.length < 2
  puts "Usage: import_mint <loot-username> <mint-username> <password>"
  exit 1
end

username, mint_username, mint_password = ARGV[0], ARGV[1], ARGV[2]

client = Mintkit::Client.new(mint_username,mint_password)

u = User.where(email:  username)[0]

u.accounts.each {|a| a.transactions.clear}
u.accounts.clear

client.accounts do |a|
  a = u.accounts.new(accounttype_id: 3, balance: a[:current_balance], name: a[:name])
  a.save
end



